### ISSUE TITLE
Change how the GitHub token is retrieved

### ISSUE THREAD

**Issue by EndBug** [Actions-R-Us/actions-tagger#48]
You can add a new input parameter named `token`, and set the default value to `${{ github.token }}`  
Here's an example:
```yaml
token:
  description: A GitHub token used for creating an Octoclient for making API calls
  default: ${{ github.token }}
```
[Link](https://github.com/peter-evans/create-pull-request/blob/master/action.yml#L4-L6)

This makes it way easier to use the action, since you don't have to use this inut unless you want to change the PAT that the action uses to create the tags, for some reason.
