### ISSUE TITLE
GitHub Actions is deprecating nodejs 12 actions which this action is currently using

### ISSUE THREAD

**Issue by diddledani** [Actions-R-Us/actions-tagger#67]
Per: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12

Recommended update:

In `action.yml` update the node runtime to:

```yaml
runs:
  using: "node16"
  main: "lib/index.js"
```
