### ISSUE TITLE
RFE: Please consider supporting `push: tags` context

### ISSUE THREAD

**Issue by jamacku** [Actions-R-Us/actions-tagger#78]
[Some repositories](https://github.com/fedora-copr/vcs-diff-lint-action/issues/6) are not used to publish releases. They only push tags. It would be nice if this action would support running on the push trigger:

```yml
on:
  push:
    tags: # tags
```
