### ISSUE TITLE
Create tags after semantic release created a pre-release

### ISSUE THREAD

**Issue by Th3S4mur41** [Actions-R-Us/actions-tagger#88]
semantic-release, created version `v2.0.0` from the `next` branch for an upcoming release

I would've expected actions-tagger to create as the `v2` tag but it didn't.
Potential root causes:
- Action absolutely requires the release or push-tag trigger
- `v2.0.0` was released as `pre-release` on GithHub and not tagged with latest.
- `v2.0.0` was created from the `next` branch, which is not the default branch (main)

Here the wokflow:
```yaml
on:
  workflow_run:
    workflows: [Checks]
    types: [completed]
    branches: [main, next, beta, alpha]

jobs:
  semantic-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/semantic-release.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}


  actions-tagger:
    needs: [semantic-release]
    runs-on: ubuntu-latest

    steps:
      - uses: Actions-R-Us/actions-tagger@latest
        with:
          publish_latest_tag: ${{ github.ref_name == 'main' }}
          token: ${{ secrets.GH_TOKEN }}
```
