### ISSUE TITLE
GitHub release must have a description for action to work

### ISSUE THREAD

**Issue by mgimenoromanadevinta** [Actions-R-Us/actions-tagger#91]
Hello

I've detected that the release in GItHub must have a description, otherwise it will complain with the following message

```
This action should only be used in a release context
If you believe this to be an error, please submit a bug report
https://github.com/Actions-R-Us/actions-tagger/issues
```

Is this the intended behavior?

Thanks!

**Comment by smac89** [comment]
@mgimenoromanadevinta can you show point to the build that exhibits this behavior?

The error you are pointing to may also be based on the fact that this action only works when you create a release, not simply a tag.

**Comment by mgimenoromanadevinta** [comment]
Hello @smac89 

This is the workflow that I'm currently using.

```yaml
name: Keep the action versions up-to-date

on:
  release:
    types:
      - released
      - published
      - edited

jobs:
  actions-tagger:
    runs-on: small
    permissions:
      contents: write
    steps:
      - uses: Actions-R-Us/actions-tagger@v2
```

All works well but if the `released`, `published` or `edited` release doesn't have a description then the following error is displayed

```
This action should only be used in a release context
If you believe this to be an error, please submit a bug report
https://github.com/Actions-R-Us/actions-tagger/issues
```
