### ISSUE TITLE
Action not working anymore ?

### ISSUE THREAD

**Issue by nvuillam** [Actions-R-Us/actions-tagger#94]
The action worked very well until 3 months ago, but since there seems to be an authorization problem.
I removed GITHUB_TOKEN var, used token parameter, removed both, added write-all permission, but nothing seems to work :/

Error: 

```sh
Using obsolete GITHUB_TOKEN environment variable: Please use token
arg instead. In most cases the default value will just work and you can
simply remove the token variable from your configuration.
Updating ref: tags/v8 to: b38cdf1f0cbe056fad4112cb7cd[9](https://github.com/oxsecurity/megalinter/actions/runs/11650500232/job/32439311091#step:3:10)9c2b574c9617
```

Pipeline:

```yaml
name: Keep GitHub tag versions up-to-date

on:
  release:
    types: [published, edited]

jobs:
  actions-tagger:
    runs-on: windows-latest
    environment:
      name: release
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - uses: Actions-R-Us/actions-tagger@v2.0.3
        with:
          publish_latest_tag: true

```

Failing job: https://github.com/oxsecurity/megalinter/actions/runs/11650500232/job/32439311091
